### ISSUE TITLE
document how to keep clarity-native-bin dependencies consistent in future releases

### ISSUE THREAD

**Issue by psq** [blockstack/clarity-js-sdk#167]
the package.json file refers to clarity-native-bin twice, once with 0.1.10 in peerDependencies, and once, correctly with 0.3.11, in devDependencies.

`npm i @blockstack/clarity` will install 0.1.10
and only `npm i --force @blockstack/clarity-native-bin@v0.3.11` will allow users to install the correct version of clarity-native-bin

`yarn add @blockstack/clarity` will not install clarity-native-bin, but at least it can be installed, with the latest with just `yarn add @blockstack/clarity-native-bin`

**Comment by agraebe** [comment]
looks like there was just a PR to update the version: https://github.com/blockstack/clarity-js-sdk/pull/172.

@psq would this fix this issue?

**Comment by psq** [comment]
yes, it should help!  not sure this will prevent the dependency from getting out of sync in the future, but automation may be more trouble that it is worth across repos, so maybe document this part of the release process so it can be manually adjusted?

**Comment by agraebe** [comment]
yeah, that would help. maybe just add a hint to the readme? looks like the release isn't mentioned yet, so we'd need someone knowledgeable to write this. maybe @LNow or @reedrosenbluth could help?

**Comment by LNow** [comment]
Because we are sill in zero major version, this issue will occur with each minor (0.4, 0.5, 0.6 etc.) release.
After the release of version 1.0.0, peerDepenency version will require manual updates only during next (2.0, 3.0 etc) releases.

Developer who executes `lerna version` or `lerna publish` and picks minor/preminor or major/premajor version have to open `packages/clarity/package.json` and bump peer dependency version accordingly (`^0.4.0`, `^0.5.0` etc. for minor releases, `^1.0.0`, `^2.0.0` etc. for major releases) before he commits changes.
