### ISSUE TITLE
provider.mine_block does not exists

### ISSUE THREAD

**Issue by friedger** [blockstack/clarity-js-sdk#76]
Clarity cli does not have a command mine_block (anymore?)

```
(node:24839) UnhandledPromiseRejectionWarning: ExecutionError: Mine block failed with bad exit code 1: Usage: /home/clarity-smart-contracts/node_modules/@blockstack/clarity-native-bin/.native-bin/clarity-sdk-v0.1.0/clarity-cli [command]
where command is one of:

  initialize         to initialize a local VM state database.
  check              to typecheck a potential contract definition.
  launch             to launch a initialize a new contract in the local state database.
  eval               to evaluate (in read-only mode) a program in a given contract context.
  eval_at_chaintip   like `eval`, but does not advance to a new block.
  eval_at_block      like `eval_at_chaintip`, but accepts a index-block-hash to evaluate at,
                     must be passed eval string via stdin.
  eval_raw           to typecheck and evaluate an expression without a contract or database context.
  repl               to typecheck and evaluate expressions in a stdin/stdout loop.
  execute            to execute a public function of a defined contract.
  generate_address   to generate a random Stacks public address for testing purposes.

    at NativeClarityBinProvider.mineBlock (/home/clarity-smart-contracts/node_modules/@blockstack/clarity/src/providers/clarityBin/index.ts:280:13)
```
Relevant code:
https://github.com/blockstack/clarity-js-sdk/blob/4317cce1bd94f48cc2866bb15abbcb63d55249bc/packages/clarity/src/providers/clarityBin/index.ts#L272

Is it possible to let time pass in the VM? Does it make sense at all?
I want to test a condition based on block height

**Comment by hstove** [comment]
Yes, it is possible! Check out the [rocket tutorial tests](https://github.com/blockstack/clarity-js-sdk/blob/master/packages/clarity-tutorials/test/rocketTutorial/rocketFactory.test.ts). It's not very well documented, but each time you query or make a TX, the block height increases. You can use that to "mine blocks" in a somewhat hacky way. Because you might not want calling a read-only function to advance a block, there is an `atChaintip` option for `eval`, which will _not_ advance by a block.
